### ISSUE TITLE
Is this available using javascript?

### ISSUE THREAD

**Issue by manishoctal** [Peteck/react-context-session#3]
This plugin seems good. My react demo having javascript. I don't want to use typescript. Do we have any version for that?

**Comment by techbech** [comment]
Yes, the library also works with JavaScript only :slightly_smiling_face:

 I've made a quick sandbox you can take a look at here [https://codesandbox.io/s/admiring-rgb-n1xn6](https://codesandbox.io/s/admiring-rgb-n1xn6)

**Comment by manishoctal** [comment]
I want to use it for my react login for admin. 
Can I use the same? for auth purpose?

**Comment by techbech** [comment]
> I want to use it for my react login for admin.
> Can I use the same? for auth purpose?

Yes, definitely. Actually, the library was made for such a purpose. But it's not limited for auth. You can put whatever you like in the data :slightly_smiling_face:

**Comment by manishoctal** [comment]
Good!! I have reviewed your codesandbox. 
This is just limited to one time only. I want to save JWT token into cookies or local storage. and use sessions on every component.

**Comment by manishoctal** [comment]
Just like: https://www.npmjs.com/package/react-session-hook
But it is now archived. But it was too good like yours. :)

**Comment by techbech** [comment]
> and use sessions on every component.

One of the cool things about this library(in my opinion), is that your components only ever react and rerenders when the data, you specify it to use/observe, changes.

So let's say you have the following in your session data
```js
{
    authToken: "some-jwt-token",
    username: "turing007",
    name: "Alan Turing",
}
```

Now, if you have a component that only needs to use `username` from the session data, you don't want that component to rerender every time that `authToken` or `name` changes. So to use the value `username` from session data in your component you'll use the `useSession` hook like following

```js
const [{ username }] = useSession()(["username"]);
```

The array `["username"]` tells the hook that you want the value of `username`, but you also only want the component, where the hook is used, to ever react/rerender when only `username` has been changed somewhere else.

Please do notice you'll always need to set the dependency array when you need a value from the session data, or else the data, in this case `username`, would always be returned by the hook as `undefined`.

> Just like: https://www.npmjs.com/package/react-session-hook
> But it is now archived. But it was too good like yours. :)

I may have misunderstood you then. This library does not have any built-in support for authentication mechanisms, like requesting and refreshing JWT tokens. The authentication process should be handled in the applications this library will be used. 

Neither will it be added, as this library aims to be a tool for any application needing any form of session data. Developers of applications, without any form of authentication, may not be satisfied with their application having unnecessary authentication code in their builds.
